recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    delete_cart,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    UserListView,
    ShoppingItemsList,
    create_shopping_item,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path("users/", UserListView.as_view(), name="user_list"),
    path(
        "shopping_items/create/",
        create_shopping_item,
        name="shopping_item_create",
    ),
    path(
        "shopping_items/",
        ShoppingItemsList.as_view(),
        name="shopping_items_list",
    ),
    path("shopping_items/delete/", delete_cart, name="shopping_items_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

recipes/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL, related_name="recipes", on_delete=models.CASCADE, null=True
    )
    description = models.TextField()
    servings = models.PositiveIntegerField(null=True)
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        USER_MODEL,
        related_name="recipe_updates",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name + " by " + str(self.author)


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(validators=[MaxValueValidator(20)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ingredients",
        on_delete=models.CASCADE,
    )
    measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
    food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

    def __str__(self):
        amount = str(self.amount)
        measure = self.measure.name
        food = self.food.name
        return amount + " " + measure + " " + food


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe",
        related_name="steps",
        on_delete=models.CASCADE,
    )
    order = models.PositiveSmallIntegerField()
    directions = models.CharField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + ". " + self.directions


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    recipe = models.ForeignKey(
        "Recipe",
        related_name="ratings",
        on_delete=models.CASCADE,
    )


class ShoppingItem(models.Model):
    user = models.ForeignKey(
        USER_MODEL, related_name="shopping_items", on_delete=models.CASCADE
    )
    food_item = models.ForeignKey(
        "FoodItem", related_name="shopping_items", on_delete=models.PROTECT
    )

    class Meta:
        unique_together = (
            "user",
            "food_item",
        )

recipes/forms.py
from django import forms
from recipes.models import Rating


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

recipes/views.py
from types import NoneType
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from recipes.models import FoodItem, Recipe, ShoppingItem, Ingredient
from recipes.forms import RatingForm


# def list_users(request):
#     users = get_user_model().all()
#     context = {"user": users}
#     return render(request, "recipes/users.html", context)


def log_rating(request, recipe_id):
    try:
        if request.method == "POST":
            form = RatingForm(request.POST)
            if form.is_valid():
                rating = form.save(commit=False)
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
        return redirect("recipe_detail", pk=recipe_id)
    except Recipe.DoesNotExist:
        return redirect("recipes_list")


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 16


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    # Allow detail view to handle post requests
    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Adding the rating form to the context
        context["rating_form"] = RatingForm()

        # Adding the list of items already in cart to the context
        food_list = []

        for item in self.request.user.shopping_items.all():
            food_list.append(item.food_item)

        context["food_list"] = food_list
        # Adding the serving size to the context

        # If view was reached by submitting the sizing
        # form on the page, use that size value
        if self.request.method == "POST":
            servings = self.request.POST.get("serving_size")

        # Else, use the default serving size of the recipe
        else:
            servings = self.object.servings

        # Add to context
        context["servings"] = servings

        return context


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "servings", "description", "image"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "servings", "description", "image"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")


class UserListView(ListView):
    model = get_user_model()
    template_name = "recipes/users.html"
    paginate_by = 16


class ShoppingItemsList(LoginRequiredMixin, ListView):
    model = ShoppingItem
    template_name = "cart/list.html"
    context_object_name = "cart"

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)


@login_required(login_url="/login")
def create_shopping_item(request):
    if request.method == "POST":

        ingredient_id = request.POST.get("ingredient_id")
        ingredient = Ingredient.objects.get(id=ingredient_id)

        try:
            ShoppingItem.objects.create(
                food_item=ingredient.food, user=request.user
            )
        except IntegrityError:
            pass

        return redirect("recipe_detail", pk=ingredient.recipe.id)


@login_required(login_url="/login")
def delete_cart(request):
    ShoppingItem.objects.filter(user=request.user).delete()
    return redirect("shopping_items_list")


# class RecipeDetailView(DetailView):
#     model = Recipe
#     template_name = "recipes/detail.html"

#     # Allow detail view to handle post requests
#     def post(self, request, *args, **kwargs):
#         return self.get(request, *args, **kwargs)

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)

#         # Adding the rating form to the context
#         context["rating_form"] = RatingForm()

#         # Adding the list of items already in cart to the context
#         food_list = []

#         for item in self.request.user.shopping_items.all():
#             food_list.append(item.food_item)

#         context["food_list"] = food_list

#         # Adding the serving size to the context

#         # If view was reached by submitting the sizing
#         # form on the page, use that size value
#         if self.request.GET.get("serving_size"):
#             servings = self.request.GET.get("serving_size")

#         # Else, use the default serving size of the recipe
#         else:
#             servings = self.object.servings

#         # Add to context
#         context["servings"] = servings

#         return context

recipes/templates/recipes/delete.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="delete-form">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ recipe }}"?</p>
                {{ form.as_p }}
                <div>
                    <button class="button">Delete</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

recipes/templates/recipes/detail.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load markdownify %}
{% block content %}
    <main class="recipe-detail">
        <div>
            <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
            <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
        </div>
        {% if recipe.image %}<img src="{{ recipe.image }}" class="pull-right">{% endif %}
        <h1>{{ recipe.name }}</h1>
        <h2>{{ recipe.author | default_if_none:"Unknown" }}</h2>
        <p>
            Created on {{ recipe.created }} |
            Updated by {{ recipe.updated_by }} |
            Updated on {{ recipe.updated }}
        </p>
        <form method="post" action="{% url 'recipe_rating' recipe.id %}">
            {% csrf_token %}
            <div class="rating-form-grid">
                {{ rating_form.as_p }}
                <button class="button">Rate</button>
            </div>
        </form>
        <p>
            Tags:
            {% for tag in recipe.tags.all %}{{ tag.word }}{% endfor %}
        </p>
        {{ recipe.description | markdownify }}
        <h2>Ingredients</h2>
        <h3>Serves: {{ servings }}</h3>
        <form method="post" action="{% url 'recipe_detail' recipe.id %}">
            {% csrf_token %}
            <input type="number"
                   name="serving_size"
                   id="serving_size"
                   min="1"
                   step="1"
                   value="1">
            <button>Update Serving Size</button>
        </form>
        <table>
            <thead>
                <tr>
                    <th colspan="2">Amount</th>
                    <th></th>
                    <th>Food item</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for ingredient in recipe.ingredients.all %}
                    <tr>
                        <td>{{ ingredient|resize_to:servings }}</td>
                        <td>{{ ingredient.measure.name }}</td>
                        <td>{{ ingredient.food.name }}</td>
                        <td>
                            {% if ingredient.food in food_list %}
                                <p>In your list</p>
                            {% else %}
                                <form method="post" action="{% url 'shopping_item_create' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="ingredient_id" value="{{ ingredient.id }}">
                                    <button>Add to Cart</button>
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h2>Steps</h2>
        <ol>
            {% for step in recipe.steps.all %}<li>{{ step.directions }}</li>{% endfor %}
        </ol>
    </main>
{% endblock content %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %}
{% block content %}
    <main class="recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Update</button>
            </div>
        </form>
    </main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'paginate.html' %}
{% block content %}
    <main class="recipe-grid">
        {% for recipe in recipe_list %}
            <div class="recipe-card">
                <h2 class="recipe-card-title">
                    <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
                </h2>
                <p class="recipe-card-date">{{ recipe.updated }}</p>
            </div>
        {% endfor %}
    </main>
{% endblock content %}

recipes/templates/recipes/new.html
{% extends 'base.html' %}
{% block content %}
    <main class="recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Create</button>
            </div>
        </form>
    </main>
{% endblock content %}

recipes/templates/recipes/users.html
{% extends 'paginate.html' %}
{% block content %}
    <main class="recipe-grid">
        {% for user in user_list %}
            <div class="recipe-card">
                <h2 class="recipe-card-title">{{ user.username }}</h2>
                {% for recipe in user.recipes.all %}<p>{{ recipe.name }}</p>{% endfor %}
            </div>
        {% endfor %}
    </main>
{% endblock content %}